name: convlstm-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu
  - seaborn
  - gdal
  - geopandas
  - rasterio
  - scikit-image
  - xarray
  - spyder
  - matplotlib
  - keras
  - keras-tuner
  - pydot
  - imbalanced-learn
